require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContactPeopleController do

  # This should return the minimal set of attributes required to create a valid
  # ContactPerson. As you add validations to ContactPerson, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "first_name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContactPeopleController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contact_people as @contact_people" do
      contact_person = ContactPerson.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contact_people).should eq([contact_person])
    end
  end

  describe "GET show" do
    it "assigns the requested contact_person as @contact_person" do
      contact_person = ContactPerson.create! valid_attributes
      get :show, {:id => contact_person.to_param}, valid_session
      assigns(:contact_person).should eq(contact_person)
    end
  end

  describe "GET new" do
    it "assigns a new contact_person as @contact_person" do
      get :new, {}, valid_session
      assigns(:contact_person).should be_a_new(ContactPerson)
    end
  end

  describe "GET edit" do
    it "assigns the requested contact_person as @contact_person" do
      contact_person = ContactPerson.create! valid_attributes
      get :edit, {:id => contact_person.to_param}, valid_session
      assigns(:contact_person).should eq(contact_person)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContactPerson" do
        expect {
          post :create, {:contact_person => valid_attributes}, valid_session
        }.to change(ContactPerson, :count).by(1)
      end

      it "assigns a newly created contact_person as @contact_person" do
        post :create, {:contact_person => valid_attributes}, valid_session
        assigns(:contact_person).should be_a(ContactPerson)
        assigns(:contact_person).should be_persisted
      end

      it "redirects to the created contact_person" do
        post :create, {:contact_person => valid_attributes}, valid_session
        response.should redirect_to(ContactPerson.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contact_person as @contact_person" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContactPerson.any_instance.stub(:save).and_return(false)
        post :create, {:contact_person => { "first_name" => "invalid value" }}, valid_session
        assigns(:contact_person).should be_a_new(ContactPerson)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContactPerson.any_instance.stub(:save).and_return(false)
        post :create, {:contact_person => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contact_person" do
        contact_person = ContactPerson.create! valid_attributes
        # Assuming there are no other contact_people in the database, this
        # specifies that the ContactPerson created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContactPerson.any_instance.should_receive(:update_attributes).with({ "first_name" => "MyString" })
        put :update, {:id => contact_person.to_param, :contact_person => { "first_name" => "MyString" }}, valid_session
      end

      it "assigns the requested contact_person as @contact_person" do
        contact_person = ContactPerson.create! valid_attributes
        put :update, {:id => contact_person.to_param, :contact_person => valid_attributes}, valid_session
        assigns(:contact_person).should eq(contact_person)
      end

      it "redirects to the contact_person" do
        contact_person = ContactPerson.create! valid_attributes
        put :update, {:id => contact_person.to_param, :contact_person => valid_attributes}, valid_session
        response.should redirect_to(contact_person)
      end
    end

    describe "with invalid params" do
      it "assigns the contact_person as @contact_person" do
        contact_person = ContactPerson.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContactPerson.any_instance.stub(:save).and_return(false)
        put :update, {:id => contact_person.to_param, :contact_person => { "first_name" => "invalid value" }}, valid_session
        assigns(:contact_person).should eq(contact_person)
      end

      it "re-renders the 'edit' template" do
        contact_person = ContactPerson.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContactPerson.any_instance.stub(:save).and_return(false)
        put :update, {:id => contact_person.to_param, :contact_person => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contact_person" do
      contact_person = ContactPerson.create! valid_attributes
      expect {
        delete :destroy, {:id => contact_person.to_param}, valid_session
      }.to change(ContactPerson, :count).by(-1)
    end

    it "redirects to the contact_people list" do
      contact_person = ContactPerson.create! valid_attributes
      delete :destroy, {:id => contact_person.to_param}, valid_session
      response.should redirect_to(contact_people_url)
    end
  end

end
