require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InternshipsController do

  # This should return the minimal set of attributes required to create a valid
  # Internship. As you add validations to Internship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "orientation" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InternshipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all internships as @internships" do
      internship = Internship.create! valid_attributes
      get :index, {}, valid_session
      assigns(:internships).should eq([internship])
    end
  end

  describe "GET show" do
    it "assigns the requested internship as @internship" do
      internship = Internship.create! valid_attributes
      get :show, {:id => internship.to_param}, valid_session
      assigns(:internship).should eq(internship)
    end
  end

  describe "GET new" do
    it "assigns a new internship as @internship" do
      get :new, {}, valid_session
      assigns(:internship).should be_a_new(Internship)
    end
  end

  describe "GET edit" do
    it "assigns the requested internship as @internship" do
      internship = Internship.create! valid_attributes
      get :edit, {:id => internship.to_param}, valid_session
      assigns(:internship).should eq(internship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Internship" do
        expect {
          post :create, {:internship => valid_attributes}, valid_session
        }.to change(Internship, :count).by(1)
      end

      it "assigns a newly created internship as @internship" do
        post :create, {:internship => valid_attributes}, valid_session
        assigns(:internship).should be_a(Internship)
        assigns(:internship).should be_persisted
      end

      it "redirects to the created internship" do
        post :create, {:internship => valid_attributes}, valid_session
        response.should redirect_to(Internship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved internship as @internship" do
        # Trigger the behavior that occurs when invalid params are submitted
        Internship.any_instance.stub(:save).and_return(false)
        post :create, {:internship => { "orientation" => "invalid value" }}, valid_session
        assigns(:internship).should be_a_new(Internship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Internship.any_instance.stub(:save).and_return(false)
        post :create, {:internship => { "orientation" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested internship" do
        internship = Internship.create! valid_attributes
        # Assuming there are no other internships in the database, this
        # specifies that the Internship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Internship.any_instance.should_receive(:update_attributes).with({ "orientation" => "MyString" })
        put :update, {:id => internship.to_param, :internship => { "orientation" => "MyString" }}, valid_session
      end

      it "assigns the requested internship as @internship" do
        internship = Internship.create! valid_attributes
        put :update, {:id => internship.to_param, :internship => valid_attributes}, valid_session
        assigns(:internship).should eq(internship)
      end

      it "redirects to the internship" do
        internship = Internship.create! valid_attributes
        put :update, {:id => internship.to_param, :internship => valid_attributes}, valid_session
        response.should redirect_to(internship)
      end
    end

    describe "with invalid params" do
      it "assigns the internship as @internship" do
        internship = Internship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Internship.any_instance.stub(:save).and_return(false)
        put :update, {:id => internship.to_param, :internship => { "orientation" => "invalid value" }}, valid_session
        assigns(:internship).should eq(internship)
      end

      it "re-renders the 'edit' template" do
        internship = Internship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Internship.any_instance.stub(:save).and_return(false)
        put :update, {:id => internship.to_param, :internship => { "orientation" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested internship" do
      internship = Internship.create! valid_attributes
      expect {
        delete :destroy, {:id => internship.to_param}, valid_session
      }.to change(Internship, :count).by(-1)
    end

    it "redirects to the internships list" do
      internship = Internship.create! valid_attributes
      delete :destroy, {:id => internship.to_param}, valid_session
      response.should redirect_to(internships_url)
    end
  end

end
